# Generated by Django 3.0.5 on 2020-11-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20201110_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.PerfilUser')),
            ],
        ),
    ]
